// This file is automatically generated from http.pac.

#ifndef http_pac_h
#define http_pac_h

#include <vector>

#ifdef WIN32
#include "binpac_win32.h"
#include "binpac_regex_win32.h"
#else
#include "binpac.h"
#include "binpac_regex.h"
#endif

#endif /* http_pac_h */
